
python-targets:
  - 2
  - 3

strictness: high
max-line-length: 132

requirements:
  - facsimile/requirements.txt

pep8:
  full: true
  options:
    hang-closing: 1

pylint:
  disable:
    - too-few-public-methods
    - redefined-builtin

