
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip
  - pip install -U setuptools
  - pip install codecov
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  - codecov

