
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  except:
    - gh-pages
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip
  - pip install -U setuptools
  - pip install codecov
  - pip install tox
script:
  - tox
after_success:
  - codecov

