[tool.poetry]
name = "pluginmgr"
version = "1.0.1"
description = "lightweight python plugin system supporting config inheritance"
authors = ["20C <code@20c.com>"]
readme = "README.md"
license = "Apache-2.0"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
]

[tool.poetry.dependencies]
python = "^3.6"
munge = "^1.0.0"

[tool.poetry.dev-dependencies]
codecov = "^2.1.10"
coverage = "^5.3"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
pytest-xdist = "^2.1.0"
tox = "^3.20.1"
black = "^20.8b1"
pyupgrade = {version = "^2.7.3", python = "^3.6.1"}
twine = "^3.2.0"
isort = "^5.6.4"
flake8 = "^3.8.4"

[tool.pytest.ini_options]
norecursedirs = ["data", "gen", ".tox"]
minversion = "6.0"
addopts = "--boxed"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
